profiles = new Array();
profiles[0]="NewSubfileType|TIFFTAG_SUBFILETYPE|254|0x00FE|subfile|reducedimage|page|mask|mrc|mixed raster content|mixed raster|newsubfile|FILETYPE_REDUCEDIMAGE|FILETYPE_PAGE|FILETYPE_MASK||A general indication of the kind of data contained in this subfile.";
profiles[1]="SubfileType|TIFFTAG_OSUBFILETYPE|255|0x00FF|subfile|reducedimage|page|OFILETYPE_IMAGE|OFILETYPE_REDUCEDIMAGE|OFILETYPE_PAGE||A general indication of the kind of data contained in this subfile.";
profiles[2]="ImageWidth|TIFFTAG_IMAGEWIDTH|256|0x0100|width|image width||The number of columns in the image, i.e., the number of pixels per row.";
profiles[3]="ImageLength|TIFFTAG_IMAGELENGTH|257|0x0101|length|height|image length|image height||The number of rows of pixels in the image.";
profiles[4]="BitsPerSample|TIFFTAG_BITSPERSAMPLE|258|0x0102|bits per sample|bits per pixel|bitdepth|bits|bitsperchannel|bits per channel||Number of bits per component.";
profiles[5]="Compression|TIFFTAG_COMPRESSION|259|0x0103|deflate|lzw|jpeg|jbig|packbits|COMPRESSION_NONE|COMPRESSION_CCITTRLE|COMPRESSION_CCITTFAX3|COMPRESSION_CCITTFAX4|COMPRESSION_LZW|COMPRESSION_OJPEG|COMPRESSION_JPEG|COMPRESSION_NEXT|COMPRESSION_CCITTRLEW|COMPRESSION_PACKBITS|COMPRESSION_THUNDERSCAN|COMPRESSION_IT8CTPAD|COMPRESSION_IT8LW|COMPRESSION_IT8MP|COMPRESSION_IT8BL|COMPRESSION_PIXARFILM|COMPRESSION_PIXARLOG|COMPRESSION_DEFLATE|COMPRESSION_ADOBE_DEFLATE|COMPRESSION_DCS|COMPRESSION_JBIG|COMPRESSION_SGILOG|COMPRESSION_SGILOG24|COMPRESSION_JP2000||Compression scheme used on the image data.";
profiles[6]="PhotometricInterpretation|TIFFTAG_PHOTOMETRIC|262|0x0106|colorspace|color space|colourspace|colour space|photometric|rgb|palette|cmyk|ycbcr|CIE L*a*b*|ICC L*a*b*|lab|ITULAB|logl|logluv|PHOTOMETRIC_MINISWHITE|PHOTOMETRIC_MINISBLACK|PHOTOMETRIC_RGB|PHOTOMETRIC_PALETTE|PHOTOMETRIC_MASK|PHOTOMETRIC_SEPARATED|PHOTOMETRIC_YCBCR|PHOTOMETRIC_CIELAB|PHOTOMETRIC_LOGL|PHOTOMETRIC_LOGLUV||The color space of the image data.";
profiles[7]="Threshholding|TIFFTAG_THRESHHOLDING|263|0x0107|THRESHHOLD_BILEVEL|THRESHHOLD_HALFTONE|THRESHHOLD_ERRORDIFFUSE||For black and white TIFF files that represent shades of gray, the technique used to convert from gray to black and white pixels.";
profiles[8]="CellWidth|TIFFTAG_CELLWIDTH|264|0x0108||The width of the dithering or halftoning matrix used to create a dithered or halftoned bilevel file.";
profiles[9]="CellLength|TIFFTAG_CELLLENGTH|265|0x0109||The length of the dithering or halftoning matrix used to create a dithered or halftoned bilevel file.";
profiles[10]="FillOrder|TIFFTAG_FILLORDER|266|0x010A|msb2lsb|lsb2msb|FILLORDER_MSB2LSB|FILLORDER_LSB2MSB||The logical order of bits within a byte.";
profiles[11]="DocumentName|TIFFTAG_DOCUMENTNAME|269|0x010D|document name||The name of the document from which this image was scanned.";
profiles[12]="ImageDescription|TIFFTAG_IMAGEDESCRIPTION|270|0x010E|image description|description||A string that describes the subject of the image.";
profiles[13]="Make|TIFFTAG_MAKE|271|0x010F|manufacturer||The scanner manufacturer.";
profiles[14]="Model|TIFFTAG_MODEL|272|0x0110||The scanner model name or number.";
profiles[15]="StripOffsets|TIFFTAG_STRIPOFFSETS|273|0x0111|strip offsets|strip offset|strip|strips||For each strip, the byte offset of that strip.";
profiles[16]="Orientation|TIFFTAG_ORIENTATION|274|0x0112|rotation|rotate|ORIENTATION_TOPLEFT|ORIENTATION_TOPRIGHT|ORIENTATION_BOTRIGHT|ORIENTATION_BOTLEFT|ORIENTATION_LEFTTOP|ORIENTATION_RIGHTTOP|ORIENTATION_RIGHTBOT|ORIENTATION_LEFTBOT||The orientation of the image with respect to the rows and columns.";
profiles[17]="SamplesPerPixel|TIFFTAG_SAMPLESPERPIXEL|277|0x0115|samples per pixel|channels per pixel|bitdepth||The number of components per pixel.";
profiles[18]="RowsPerStrip|TIFFTAG_ROWSPERSTRIP|278|0x0116|strips|strip|rows per strip||The number of rows per strip.";
profiles[19]="StripByteCounts|TIFFTAG_STRIPBYTECOUNTS|279|0x0117|strips|strip||For each strip, the number of bytes in the strip after compression.";
profiles[20]="MinSampleValue|TIFFTAG_MINSAMPLEVALUE|280|0x0118|min sample value|sample value||The minimum component value used.";
profiles[21]="MaxSampleValue|TIFFTAG_MAXSAMPLEVALUE|281|0x0119|max sample value|sample value||The maximum component value used.";
profiles[22]="XResolution|TIFFTAG_XRESOLUTION|282|0x011A|x resolution|resolution|dpi|density||The number of pixels per ResolutionUnit in the ImageWidth direction.";
profiles[23]="YResolution|TIFFTAG_YRESOLUTION|283|0x011B|y resolution|resolution|dpi|density||The number of pixels per ResolutionUnit in the ImageLength direction.";
profiles[24]="PlanarConfiguration|TIFFTAG_PLANARCONFIG|284|0x011C|planar|chunky|planarconfig|planar config|planar configuration|PLANARCONFIG_CONTIG|PLANARCONFIG_SEPARATE||How the components of each pixel are stored.";
profiles[25]="PageName|TIFFTAG_PAGENAME|285|0x011D|page name||The name of the page from which this image was scanned.";
profiles[26]="XPosition|TIFFTAG_XPOSITION|286|0x011E|x position|position||X position of the image.";
profiles[27]="YPosition|TIFFTAG_YPOSITION|287|0x011F|y position|position||Y position of the image.";
profiles[28]="FreeOffsets|TIFFTAG_FREEOFFSETS|288|0x0120||For each string of contiguous unused bytes in a TIFF file, the byte offset of the string.";
profiles[29]="FreeByteCounts|TIFFTAG_FREEBYTECOUNTS|289|0x0121||For each string of contiguous unused bytes in a TIFF file, the number of bytes in the string.";
profiles[30]="GrayResponseUnit|TIFFTAG_GRAYRESPONSEUNIT|290|0x0122|gray response unit|gray response|grayresponse|GRAYRESPONSEUNIT_10S|GRAYRESPONSEUNIT_100S|GRAYRESPONSEUNIT_1000S|GRAYRESPONSEUNIT_10000S|GRAYRESPONSEUNIT_100000S||The precision of the information contained in the GrayResponseCurve.";
profiles[31]="GrayResponseCurve|TIFFTAG_GRAYRESPONSECURVE|291|0x0123|gray response curve|gray response|grayresponse||For grayscale data, the optical density of each possible pixel value.";
profiles[32]="T4Options|TIFFTAG_GROUP3OPTIONS|292|0x0124|T4 options|G3 options|group 3|group3|group3options|group 3 options|group 3 fax options|fax 3 options|g3|group 3 fax|fax 3|GROUP3OPT_2DENCODING|GROUP3OPT_UNCOMPRESSED|GROUP3OPT_FILLBITS||Options for Group 3 Fax compression";
profiles[33]="T6Options|TIFFTAG_GROUP4OPTIONS|293|0x0125|T6 options|G4 options|group 4|group4|group4options|group 4 options|group 4 fax options|fax 4 options|g4|group 4 fax|fax 4|GROUP4OPT_UNCOMPRESSED||Options for Group 4 Fax compression";
profiles[34]="ResolutionUnit|TIFFTAG_RESOLUTIONUNIT|296|0x0128|resolution unit|resolution|dpi|density|RESUNIT_NONE|RESUNIT_INCH|RESUNIT_CENTIMETER||The unit of measurement for XResolution and YResolution.";
profiles[35]="PageNumber|TIFFTAG_PAGENUMBER|297|0x0129|page number||The page number of the page from which this image was scanned.";
profiles[36]="TransferFunction|TIFFTAG_TRANSFERFUNCTION|301|0x012D|transfer function|transfer||Describes a transfer function for the image in tabular style.";
profiles[37]="Software|TIFFTAG_SOFTWARE|305|0x0131||Name and version number of the software package(s) used to create the image.";
profiles[38]="DateTime|TIFFTAG_DATETIME|306|0x0132|date time|date|time||Date and time of image creation.";
profiles[39]="Artist|TIFFTAG_ARTIST|315|0x013B||Person who created the image.";
profiles[40]="HostComputer|TIFFTAG_HOSTCOMPUTER|316|0x013C|host computer|host||The computer and/or operating system in use at the time of image creation.";
profiles[41]="Predictor|TIFFTAG_PREDICTOR|317|0x013D|PREDICTOR_NONE|PREDICTOR_HORIZONTAL|PREDICTOR_FLOATINGPOINT||A mathematical operator that is applied to the image data before an encoding scheme is applied.";
profiles[42]="WhitePoint|TIFFTAG_WHITEPOINT|318|0x013E||The chromaticity of the white point of the image.";
profiles[43]="PrimaryChromaticities|TIFFTAG_PRIMARYCHROMATICITIES|319|0x013F|primary chromaticities|chromaticities||The chromaticities of the primaries of the image.";
profiles[44]="ColorMap|TIFFTAG_COLORMAP|320|0x0140|color map|palette||A color map for palette color images.";
profiles[45]="HalftoneHints|TIFFTAG_HALFTONEHINTS|321|0x0141|halftone hints|halftone||Conveys to the halftone function the range of gray levels within a colorimetrically-specified image that should retain tonal detail.";
profiles[46]="TileWidth|TIFFTAG_TILEWIDTH|322|0x0142|tile width|tile|tiles|width||The tile width in pixels. This is the number of columns in each tile.";
profiles[47]="TileLength|TIFFTAG_TILELENGTH|323|0x0143|tile length|tile height|tile|tiles|height||The tile length (height) in pixels. This is the number of rows in each tile.";
profiles[48]="TileOffsets|TIFFTAG_TILEOFFSETS|324|0x0144|tile offsets|tile offset|tile|tiles||For each tile, the byte offset of that tile, as compressed and stored on disk.";
profiles[49]="TileByteCounts|TIFFTAG_TILEBYTECOUNTS|325|0x0145|tile bytecounts|tile bytecount|tile byte counts|tile byte count|tile|tiles||For each tile, the number of (compressed) bytes in that tile.";
profiles[50]="BadFaxLines|TIFFTAG_BADFAXLINES|326|0x0146|bad fax lines|badfaxline|bad fax line|tiff-f|tiff f|fax|internet fax||Used in the TIFF-F standard, denotes the number of 'bad' scan lines encountered by the facsimile device.";
profiles[51]="CleanFaxData|TIFFTAG_CLEANFAXDATA|327|0x0147|clean fax data|tiff-f|tiff f|fax|internet fax|CLEANFAXDATA_CLEAN|CLEANFAXDATA_REGENERATED|CLEANFAXDATA_UNCLEAN||Used in the TIFF-F standard, indicates if 'bad' lines encountered during reception are stored in the data, or if 'bad' lines have been replaced by the receiver.";
profiles[52]="ConsecutiveBadFaxLines|TIFFTAG_CONSECUTIVEBADFAXLINES|328|0x0148|consecutive bad fax lines|bad fax lines|badfaxline|bad fax line|tiff-f|tiff f|fax|internet fax||Used in the TIFF-F standard, denotes the maximum number of consecutive 'bad' scanlines received.";
profiles[53]="SubIFDs|TIFFTAG_SUBIFD|330|0x014A|subifd|child ifd|child||Offset to child IFDs.";
profiles[54]="InkSet|TIFFTAG_INKSET|332|0x014C|ink set|ink|cmyk|INKSET_CMYK||The set of inks used in a separated (PhotometricInterpretation=5) image.";
profiles[55]="InkNames|TIFFTAG_INKNAMES|333|0x014D|ink names|ink name|ink|cmyk||The name of each ink used in a separated image.";
profiles[56]="NumberOfInks|TIFFTAG_NUMBEROFINKS|334|0x014E|number of inks|ink|cmyk||The number of inks.";
profiles[57]="DotRange|TIFFTAG_DOTRANGE|336|0x0150|dot range||The component values that correspond to a 0% dot and 100% dot.";
profiles[58]="TargetPrinter|TIFFTAG_TARGETPRINTER|337|0x0151|target printer|printer||A description of the printing environment for which this separation is intended.";
profiles[59]="ExtraSamples|TIFFTAG_EXTRASAMPLES|338|0x0152|extra samples|extra sample|extra channels|extra channel|channel|alpha|transparency|bitdepth|EXTRASAMPLE_UNSPECIFIED|EXTRASAMPLE_ASSOCALPHA|EXTRASAMPLE_UNASSALPHA||Description of extra components.";
profiles[60]="SampleFormat|TIFFTAG_SAMPLEFORMAT|339|0x0153|sample format|sample|datatype|data format|bitdepth|SAMPLEFORMAT_UINT|SAMPLEFORMAT_INT|SAMPLEFORMAT_IEEEFP|SAMPLEFORMAT_VOID|SAMPLEFORMAT_COMPLEXINT|SAMPLEFORMAT_COMPLEXIEEEFP||Specifies how to interpret each data sample in a pixel.";
profiles[61]="SMinSampleValue|TIFFTAG_SMINSAMPLEVALUE|340|0x0154|min sample value|minimum sample value|sample value||Specifies the minimum sample value.";
profiles[62]="SMaxSampleValue|TIFFTAG_SMAXSAMPLEVALUE|341|0x0155|max sample value|maximum sample value|sample value||Specifies the maximum sample value.";
profiles[63]="TransferRange|-|342|0x0156|transfer range|transfer||Expands the range of the TransferFunction.";
profiles[64]="ClipPath|-|343|0x0157|clip path|clip||Mirrors the essentials of PostScript's path creation functionality.";
profiles[65]="XClipPathUnits|-|344|0x0158|clippath units|clip path units|clip path|clip||The number of units that span the width of the image, in terms of integer ClipPath coordinates.";
profiles[66]="YClipPathUnits|-|345|0x0159|clippath units|clip path units|clip path|clip||The number of units that span the height of the image, in terms of integer ClipPath coordinates.";
profiles[67]="Indexed|-|346|0x015A|palette||Aims to broaden the support for indexed images to include support for any color space.";
profiles[68]="JPEGTables|TIFFTAG_JPEGTABLES|347|0x015B|jpeg tables|jpeg||JPEG quantization and/or Huffman tables.";
profiles[69]="OPIProxy|-|351|0x015F|opi proxy|opi||OPI-related.";
profiles[70]="GlobalParametersIFD|-|400|0x0190|global parameters ifd|globalparameters|global parameters|tiff-fx|tiff fx|fax|internet fax||Used in the TIFF-FX standard to point to an IFD containing tags that are globally applicable to the complete TIFF file.";
profiles[71]="ProfileType|-|401|0x0191|profile type|profile|tiff-fx|tiff fx|fax|internet fax||Used in the TIFF-FX standard, denotes the type of data stored in this file or IFD.";
profiles[72]="FaxProfile|-|402|0x0192|fax profile|profile|tiff-fx|tiff fx|fax|internet fax||Used in the TIFF-FX standard, denotes the 'profile' that applies to this file.";
profiles[73]="CodingMethods|-|403|0x0193|coding methods|tiff-fx|tiff fx|fax|internet fax||Used in the TIFF-FX standard, indicates which coding methods are used in the file.";
profiles[74]="VersionYear|-|404|0x0194|version year|tiff-fx|tiff fx|fax|internet fax||Used in the TIFF-FX standard, denotes the year of the standard specified by the FaxProfile field.";
profiles[75]="ModeNumber|-|405|0x0195|mode number|tiff-fx|tiff fx|fax|internet fax||Used in the TIFF-FX standard, denotes the mode of the standard specified by the FaxProfile field.";
profiles[76]="Decode|-|433|0x01B1|tiff-f|tiff f|tiff-fx|tiff fx|fax|internet fax|ITULAB||Used in the TIFF-F and TIFF-FX standards, holds information about the ITULAB (PhotometricInterpretation = 10) encoding.";
profiles[77]="DefaultImageColor|-|434|0x01B2|default image color|default color|mrc|mixed raster content|mixed raster||Defined in the Mixed Raster Content part of RFC 2301, is the default color needed in areas where no image is available.";
profiles[78]="JPEGProc|TIFFTAG_JPEGPROC|512|0x0200|jpeg proc|jpeg process|old-style jpeg|jpeg|ojpeg|sequential|lossless|huffman|JPEGPROC_BASELINE|JPEGPROC_LOSSLESS||Old-style JPEG compression field. TechNote2 invalidates this part of the specification.";
profiles[79]="JPEGInterchangeFormat|TIFFTAG_JPEGIFOFFSET|513|0x0201|jpeg interchange format|jpeg interchange|old-style jpeg|jpeg|ojpeg||Old-style JPEG compression field. TechNote2 invalidates this part of the specification.";
profiles[80]="JPEGInterchangeFormatLength|TIFFTAG_JPEGIFBYTECOUNT|514|0x0202|jpeg interchange format|jpeg interchange format length|jpeg interchange|old-style jpeg|jpeg|ojpeg||Old-style JPEG compression field. TechNote2 invalidates this part of the specification.";
profiles[81]="JPEGRestartInterval|TIFFTAG_JPEGRESTARTINTERVAL|515|0x0203|jpeg restart interval|jpeg restart|old-style jpeg|jpeg||Old-style JPEG compression field. TechNote2 invalidates this part of the specification.";
profiles[82]="JPEGLosslessPredictors|TIFFTAG_JPEGLOSSLESSPREDICTORS|517|0x0205|jpeg lossless predictors|jpeg lossless|old-style jpeg|jpeg||Old-style JPEG compression field. TechNote2 invalidates this part of the specification.";
profiles[83]="JPEGPointTransforms|TIFFTAG_JPEGPOINTTRANSFORM|518|0x0206|jpeg point transforms|old-style jpeg|jpeg||Old-style JPEG compression field. TechNote2 invalidates this part of the specification.";
profiles[84]="JPEGQTables|TIFFTAG_JPEGQTABLES|519|0x0207|jpeg qtables|jpeg q tables|jpeg tables|old-style jpeg|jpeg|ojpeg|qtables|q tables|quantization|quantization tables||Old-style JPEG compression field. TechNote2 invalidates this part of the specification.";
profiles[85]="JPEGDCTables|TIFFTAG_JPEGDCTABLES|520|0x0208|jpeg dctables|jpeg dc tables|jpeg tables|old-style jpeg|jpeg||Old-style JPEG compression field. TechNote2 invalidates this part of the specification.";
profiles[86]="JPEGACTables|TIFFTAG_JPEGACTABLES|521|0x0209|jpeg actables|jpeg ac tables|jpeg tables|old-style jpeg|jpeg||Old-style JPEG compression field. TechNote2 invalidates this part of the specification.";
profiles[87]="YCbCrCoefficients|TIFFTAG_YCBCRCOEFFICIENTS|529|0x0211|ycbcr coefficients|ycbcr||The transformation from RGB to YCbCr image data.";
profiles[88]="YCbCrSubSampling|TIFFTAG_YCBCRSUBSAMPLING|530|0x0212|ycbcr subsampling|ycbcr|chromasubsampling|chroma subsampling|subsampling||Specifies the subsampling factors used for the chrominance components of a YCbCr image.";
profiles[89]="YCbCrPositioning|TIFFTAG_YCBCRPOSITIONING|531|0x0213|ycbcr positioning|ycbcr|chromapositioning|chroma positioning|subsampling|YCBCRPOSITION_CENTERED|YCBCRPOSITION_COSITED||Specifies the positioning of subsampled chrominance components relative to luminance samples.";
profiles[90]="ReferenceBlackWhite|TIFFTAG_REFERENCEBLACKWHITE|532|0x0214|reference black white||Specifies a pair of headroom and footroom image data values (codes) for each pixel component.";
profiles[91]="StripRowCounts|-|559|0x022F|strip row counts|striprowcount|strip row count|mrc|mixed raster content|mixed raster||Defined in the Mixed Raster Content part of RFC 2301, used to replace RowsPerStrip for IFDs with variable-sized strips.";
profiles[92]="XMP|TIFFTAG_XMLPACKET|700|0x02BC||XML packet containing XMP metadata";
profiles[93]="ImageID|-|32781|0x800D|opi||OPI-related.";
profiles[94]="Wang Annotation|-|32932|0x80A4|annotation||Annotation data, as used in 'Imaging for Windows'.";
profiles[95]="Copyright|TIFFTAG_COPYRIGHT|33432|0x8298||Copyright notice.";
profiles[96]="MD FileTag|-|33445|0x82A5|molecular dynamics|gel|md|filetag||Specifies the pixel data format encoding in the Molecular Dynamics GEL file format.";
profiles[97]="MD ScalePixel|-|33446|0x82A6|molecular dynamics|gel|md|scalepixel||Specifies a scale factor in the Molecular Dynamics GEL file format.";
profiles[98]="MD ColorTable|-|33447|0x82A7|molecular dynamics|gel|md|colortable||Used to specify the conversion from 16bit to 8bit in the Molecular Dynamics GEL file format.";
profiles[99]="MD LabName|-|33448|0x82A8|molecular dynamics|gel|md|labname||Name of the lab that scanned this file, as used in the Molecular Dynamics GEL file format.";
profiles[100]="MD SampleInfo|-|33449|0x82A9|molecular dynamics|gel|md|sampleinfo||Information about the sample, as used in the Molecular Dynamics GEL file format.";
profiles[101]="MD PrepDate|-|33450|0x82AA|molecular dynamics|gel|md|prepdate||Date the sample was prepared, as used in the Molecular Dynamics GEL file format.";
profiles[102]="MD PrepTime|-|33451|0x82AB|molecular dynamics|gel|md|preptime||Time the sample was prepared, as used in the Molecular Dynamics GEL file format.";
profiles[103]="MD FileUnits|-|33452|0x82AC|molecular dynamics|gel|md|fileunits||Units for data in this file, as used in the Molecular Dynamics GEL file format.";
profiles[104]="ModelPixelScaleTag|-|33550|0x830E|transformation|geotiff|model pixel scale tag|modelpixelscale|model pixel scale|pixelscale|pixel scale||Used in interchangeable GeoTIFF files.";
profiles[105]="IPTC|TIFFTAG_RICHTIFFIPTC|33723|0x83BB||IPTC (International Press Telecommunications Council) metadata.";
profiles[106]="INGR Packet Data Tag|-|33918|0x847E|intergraph|packet data tag|packet data|packet||Intergraph Application specific storage.";
profiles[107]="INGR Flag Registers|-|33919|0x847F|intergraph|flag registers||Intergraph Application specific flags.";
profiles[108]="IrasB Transformation Matrix|-|33920|0x8480|irasb|intergraph|transformation matrix|transformation||Originally part of Intergraph's GeoTIFF tags, but likely understood by IrasB only.";
profiles[109]="ModelTiepointTag|-|33922|0x8482|geotiff|intergraph|model tiepoint tag|model tiepoint|georeference tag|georeference|modeltiepoint||Originally part of Intergraph's GeoTIFF tags, but now used in interchangeable GeoTIFF files.";
profiles[110]="ModelTransformationTag|-|34264|0x85D8|geotiff|model transformation tag|model transformation|transformation||Used in interchangeable GeoTIFF files.";
profiles[111]="Photoshop|TIFFTAG_PHOTOSHOP|34377|0x8649||Collection of Photoshop 'Image Resource Blocks'.";
profiles[112]="Exif IFD|TIFFTAG_EXIFIFD|34665|0x8769|exif||A pointer to the Exif IFD.";
profiles[113]="ICC Profile|TIFFTAG_ICCPROFILE|34675|0x8773|iccprofile|icc||ICC profile data.";
profiles[114]="ImageLayer|-|34732|0x87AC|image layer|mrc|mixed raster content|mixed raster||Defined in the Mixed Raster Content part of RFC 2301, used to denote the particular function of this Image in the mixed raster scheme.";
profiles[115]="GeoKeyDirectoryTag|-|34735|0x87AF|geotiff|projectioninfotag|coordsysteminfotag|geo key directory tag|geo key directory|key directory|geo key|geo keys|geokeys|projection info tag|projection info|projection|coord system info tag|coord system info|coord system||Used in interchangeable GeoTIFF files.";
profiles[116]="GeoDoubleParamsTag|-|34736|0x87B0|geotiff|geo double params tag|geo double params|double params tag|double params||Used in interchangeable GeoTIFF files.";
profiles[117]="GeoAsciiParamsTag|-|34737|0x87B1|geotiff|geo ascii params tag|geo ascii params|ascii params tag|ascii params||Used in interchangeable GeoTIFF files.";
profiles[118]="GPS IFD|TIFFTAG_GPSIFD|34853|0x8825|gps|exif||A pointer to the Exif-related GPS Info IFD.";
profiles[119]="HylaFAX FaxRecvParams|TIFFTAG_FAXRECVPARAMS|34908|0x885C|faxrecvparams|fax|hylafax||Used by HylaFAX.";
profiles[120]="HylaFAX FaxSubAddress|TIFFTAG_FAXSUBADDRESS|34909|0x885D|faxsubaddress|fax|hylafax||Used by HylaFAX.";
profiles[121]="HylaFAX FaxRecvTime|TIFFTAG_FAXRECVTIME|34910|0x885E|faxrecvtime|fax|hylafax||Used by HylaFAX.";
profiles[122]="ImageSourceData|-|37724|0x935C||Used by Adobe Photoshop.";
profiles[123]="Interoperability IFD|TIFFTAG_INTEROPERABILITYIFD|40965|0xA005|interoperability|exif||A pointer to the Exif-related Interoperability IFD.";
profiles[124]="GDAL_METADATA|-|42112|0xA480|gdal|metadata|gdal metadata|xml||Used by the GDAL library, holds an XML list of name=value 'metadata' values about the image as a whole, and about specific samples.";
profiles[125]="GDAL_NODATA|-|42113|0xA481|gdal|nodata|gdal nodata|background|transparent|transparency|alpha||Used by the GDAL library, contains an ASCII encoded nodata or background pixel value.";
profiles[126]="Oce Scanjob Description|-|50215|0xC427|oce|scanticket|scanjob|scanjob description||Used in the Oce scanning process.";
profiles[127]="Oce Application Selector|-|50216|0xC428|oce|scanticket|application|application selector||Used in the Oce scanning process.";
profiles[128]="Oce Identification Number|-|50217|0xC429|oce|scanticket|identification|identification number||Used in the Oce scanning process.";
profiles[129]="Oce ImageLogic Characteristics|-|50218|0xC42A|oce|scanticket|imagelogic|imagelogic characteristics||Used in the Oce scanning process.";
profiles[130]="DNGVersion|TIFFTAG_DNGVERSION|50706|0xC612|DNG|dng version||Used in IFD 0 of DNG files.";
profiles[131]="DNGBackwardVersion|TIFFTAG_DNGBACKWARDVERSION|50707|0xC613|dng|dng version|dng backward version||Used in IFD 0 of DNG files.";
profiles[132]="UniqueCameraModel|TIFFTAG_UNIQUECAMERAMODEL|50708|0xC614|dng|unique camera model|dng camera model|camera model||Used in IFD 0 of DNG files.";
profiles[133]="LocalizedCameraModel|TIFFTAG_LOCALIZEDCAMERAMODEL|50709|0xC615|dng|dng camera model|unique camera model|dng unique camera model|camera model||Used in IFD 0 of DNG files.";
profiles[134]="CFAPlaneColor|TIFFTAG_CFAPLANECOLOR|50710|0xC616|dng|cfa plane color|dng cfa plane color|plane color|dng plane color|cfa plane|dng cfa plane|cfa|dng cfa||Used in Raw IFD of DNG files.";
profiles[135]="CFALayout|TIFFTAG_CFALAYOUT|50711|0xC617|dng|cfa layout|dng cfa layout|cfa|dng cfa||Used in Raw IFD of DNG files.";
profiles[136]="LinearizationTable|TIFFTAG_LINEARIZATIONTABLE|50712|0xC618|dng|linearization table|dng linearization table|linearization|dng linearization||Used in Raw IFD of DNG files.";
profiles[137]="BlackLevelRepeatDim|TIFFTAG_BLACKLEVELREPEATDIM|50713|0xC619|dng|dng black level repeat dim|black level repeat dim|dng black level repeat|black level repeat|dng black level|black level||Used in Raw IFD of DNG files.";
profiles[138]="BlackLevel|TIFFTAG_BLACKLEVEL|50714|0xC61A|dng|dng black level|black level||Used in Raw IFD of DNG files.";
profiles[139]="BlackLevelDeltaH|TIFFTAG_BLACKLEVELDELTAH|50715|0xC61B|dng|dng black level delta h|black level delta h|dng black level delta|black level delta|dng black level|black level||Used in Raw IFD of DNG files.";
profiles[140]="BlackLevelDeltaV|TIFFTAG_BLACKLEVELDELTAV|50716|0xC61C|dng|dng black level delta v|black level delta v|dng black level delta|black level delta|dng black level|black level||Used in Raw IFD of DNG files.";
profiles[141]="WhiteLevel|TIFFTAG_WHITELEVEL|50717|0xC61D|dng|dng white level|white level||Used in Raw IFD of DNG files.";
profiles[142]="DefaultScale|TIFFTAG_DEFAULTSCALE|50718|0xC61E|dng|dng default scale|default scale||Used in Raw IFD of DNG files.";
profiles[143]="DefaultCropOrigin|TIFFTAG_DEFAULTCROPORIGIN|50719|0xC61F|dng|dng default crop origin|default crop origin|dng crop origin|crop origin|dng crop|crop||Used in Raw IFD of DNG files.";
profiles[144]="DefaultCropSize|TIFFTAG_DEFAULTCROPSIZE|50720|0xC620|dng|dng default crop size|default crop size|dng crop size|crop size|dng crop|crop||Used in Raw IFD of DNG files.";
profiles[145]="ColorMatrix1|TIFFTAG_COLORMATRIX1|50721|0xC621|dng|dng color matrix 1|color matrix 1|dng color matrix|color matrix||Used in IFD 0 of DNG files.";
profiles[146]="ColorMatrix2|TIFFTAG_COLORMATRIX2|50722|0xC622|dng|dng color matrix 2|color matrix 2|dng color matrix|color matrix||Used in IFD 0 of DNG files.";
profiles[147]="CameraCalibration1|TIFFTAG_CAMERACALIBRATION1|50723|0xC623|dng|dng camera calibration 1|camera calibration 1|dng camera calibration|camera calibration|dng calibration|calibration||Used in IFD 0 of DNG files.";
profiles[148]="CameraCalibration2|TIFFTAG_CAMERACALIBRATION2|50724|0xC624|dng|dng camera calibration 2|camera calibration 2|dng camera calibration|camera calibration|dng calibration|calibration||Used in IFD 0 of DNG files.";
profiles[149]="ReductionMatrix1|TIFFTAG_REDUCTIONMATRIX1|50725|0xC625|dng|dng reduction matrix 1|reduction matrix 1|dng reduction matrix|reduction matrix||Used in IFD 0 of DNG files.";
profiles[150]="ReductionMatrix2|TIFFTAG_REDUCTIONMATRIX2|50726|0xC626|dng|dng reduction matrix 2|reduction matrix 2|dng reduction matrix|reduction matrix||Used in IFD 0 of DNG files.";
profiles[151]="AnalogBalance|TIFFTAG_ANALOGBALANCE|50727|0xC627|dng|dng analog balance|analog balance|dng balance|balance||Used in IFD 0 of DNG files.";
profiles[152]="AsShotNeutral|TIFFTAG_ASSHOTNEUTRAL|50728|0xC628|dng|dng as shot neutral|as shot neutral|dng shot neutral|shot neutral|dng as||Used in IFD 0 of DNG files.";
profiles[153]="AsShotWhiteXY|TIFFTAG_ASSHOTWHITEXY|50729|0xC629|dng|dng as shot white xy|as shot white xy|dng shot white xy|shot white xy|dng shot white|shot white|dng as||Used in IFD 0 of DNG files.";
profiles[154]="BaselineExposure|TIFFTAG_BASELINEEXPOSURE|50730|0xC62A|dng|dng baseline exposure|baseline exposure|dng exposure|exposure||Used in IFD 0 of DNG files.";
profiles[155]="BaselineNoise|TIFFTAG_BASELINENOISE|50731|0xC62B|dng|dng baseline noise|baseline noise|dng noise|noise||Used in IFD 0 of DNG files.";
profiles[156]="BaselineSharpness|TIFFTAG_BASELINESHARPNESS|50732|0xC62C|dng|dng baseline sharpness|baseline sharpness|dng sharpness|sharpness||Used in IFD 0 of DNG files.";
profiles[157]="BayerGreenSplit|TIFFTAG_BAYERGREENSPLIT|50733|0xC62D|dng|dng bayer green split|bayer green split|dng bayer|bayer||Used in Raw IFD of DNG files.";
profiles[158]="LinearResponseLimit|TIFFTAG_LINEARRESPONSELIMIT|50734|0xC62E|dng|dng linear response limit|linear response limit||Used in IFD 0 of DNG files.";
profiles[159]="CameraSerialNumber|TIFFTAG_CAMERASERIALNUMBER|50735|0xC62F|dng|dng camera serial number|camera serial number||Used in IFD 0 of DNG files.";
profiles[160]="LensInfo|TIFFTAG_LENSINFO|50736|0xC630|dng|dng lens info|lens info||Used in IFD 0 of DNG files.";
profiles[161]="ChromaBlurRadius|TIFFTAG_CHROMABLURRADIUS|50737|0xC631|dng|dng chroma blur radius|chroma blur radius||Used in Raw IFD of DNG files.";
profiles[162]="AntiAliasStrength|TIFFTAG_ANTIALIASSTRENGTH|50738|0xC632|dng|dng anti alias strength|anti alias strength|dng anti alias|anti alias||Used in Raw IFD of DNG files.";
profiles[163]="DNGPrivateData|TIFFTAG_DNGPRIVATEDATA|50740|0xC634|dng|dng private data|private data||Used in IFD 0 of DNG files.";
profiles[164]="MakerNoteSafety|TIFFTAG_MAKERNOTESAFETY|50741|0xC635|dng|dng maker note safety|maker note safety|maker note||Used in IFD 0 of DNG files.";
profiles[165]="CalibrationIlluminant1|TIFFTAG_CALIBRATIONILLUMINANT1|50778|0xC65A|dng|dng calibration illuminant 1|calibration illuminant 1|dng calibration illuminant|calibration illuminant|dng calibration|calibration||Used in IFD 0 of DNG files.";
profiles[166]="CalibrationIlluminant2|TIFFTAG_CALIBRATIONILLUMINANT2|50779|0xC65B|dng|dng calibration illuminant 2|calibration illuminant 2|dng calibration illuminant|calibration illuminant|dng calibration|calibration||Used in IFD 0 of DNG files.";
profiles[167]="BestQualityScale|TIFFTAG_BESTQUALITYSCALE|50780|0xC65C|dng|dng best quality scale|best quality scale||Used in Raw IFD of DNG files.";
profiles[168]="Alias Layer Metadata|-|50784|0xC660|Alias Sketchbook Pro|Alias|Sketchbook Pro|Sketchbook|Alias layer||Alias Sketchbook Pro layer usage description.";
profiles[169]="ExposureTime|-|33434|0x829A|exposure time|exposure||Exposure time, given in seconds.";
profiles[170]="FNumber|-|33437|0x829D|f number||The F number.";
profiles[171]="ExposureProgram|-|34850|0x8822|exposure program|exposure||The class of the program used by the camera to set exposure when the picture is taken.";
profiles[172]="SpectralSensitivity|-|34852|0x8824|spectral sensitivity||Indicates the spectral sensitivity of each channel of the camera used.";
profiles[173]="ISOSpeedRatings|-|34855|0x8827|speedratings|speed ratings|speed||Indicates the ISO Speed and ISO Latitude of the camera or input device as specified in ISO 12232.";
profiles[174]="OECF|-|34856|0x8828||Indicates the Opto-Electric Conversion Function (OECF) specified in ISO 14524.";
profiles[175]="ExifVersion|-|36864|0x9000|exif|exif version|version||The version of the supported Exif standard.";
profiles[176]="DateTimeOriginal|-|36867|0x9003|date time original|date time|datetime|date|time||The date and time when the original image data was generated.";
profiles[177]="DateTimeDigitized|-|36868|0x9004|date time digitized|date time|datetime|date|time||The date and time when the image was stored as digital data.";
profiles[178]="ComponentsConfiguration|-|37121|0x9101|components|components configuration|exif components||Specific to compressed data; specifies the channels and complements PhotometricInterpretation";
profiles[179]="CompressedBitsPerPixel|-|37122|0x9102|compressed bits per pixel|bits per pixel|bitsperpixel|exif bits per pixel|exif bitsperpixel||Specific to compressed data; states the compressed bits per pixel.";
profiles[180]="ShutterSpeedValue|-|37377|0x9201|shutter speed value|shutter speed|shutterspeed|shutter||Shutter speed.";
profiles[181]="ApertureValue|-|37378|0x9202|aperture value|aperture||The lens aperture.";
profiles[182]="BrightnessValue|-|37379|0x9203|brightness value|brightness||The value of brightness.";
profiles[183]="ExposureBiasValue|-|37380|0x9204|exposure bias value|exposure bias|exposurebias|exposure|bias||The exposure bias.";
profiles[184]="MaxApertureValue|-|37381|0x9205|max aperture value|max aperture|maxaperture|aperture value|aperture||The smallest F number of the lens.";
profiles[185]="SubjectDistance|-|37382|0x9206|subject distance||The distance to the subject, given in meters.";
profiles[186]="MeteringMode|-|37383|0x9207|metering mode|metering||The metering mode.";
profiles[187]="LightSource|-|37384|0x9208|light source|light||The kind of light source.";
profiles[188]="Flash|-|37385|0x9209||Indicates the status of flash when the image was shot.";
profiles[189]="FocalLength|-|37386|0x920A|focal length||The actual focal length of the lens, in mm.";
profiles[190]="SubjectArea|-|37396|0x9214|subject area||Indicates the location and area of the main subject in the overall scene.";
profiles[191]="MakerNote|-|37500|0x927C|exif makernote|exif maker note|maker note||Manufacturer specific information.";
profiles[192]="UserComment|-|37510|0x9286|user comment||Keywords or comments on the image; complements ImageDescription.";
profiles[193]="SubsecTime|-|37520|0x9290|date time|datetime|date|time|seconds||A tag used to record fractions of seconds for the DateTime tag.";
profiles[194]="SubsecTimeOriginal|-|37521|0x9291|datetimeoriginal|date time|datetime|date|time|seconds||A tag used to record fractions of seconds for the DateTimeOriginal tag.";
profiles[195]="SubsecTimeDigitized|-|37522|0x9292|datetimedigitized|date time|datetime|date|time|seconds||A tag used to record fractions of seconds for the DateTimeDigitized tag.";
profiles[196]="FlashpixVersion|-|40960|0xA000|flashpix|flashpix version||The Flashpix format version supported by a FPXR file.";
profiles[197]="ColorSpace|-|40961|0xA001|color space|exif colorspace|exif color space|exif color||The color space information tag is always recorded as the color space specifier.";
profiles[198]="PixelXDimension|-|40962|0xA002|pixel x dimension|pixel xdimension|xdimension|x dimension||Specific to compressed data; the valid width of the meaningful image.";
profiles[199]="PixelYDimension|-|40963|0xA003|pixel y dimension|pixel ydimension|ydimension|y dimension||Specific to compressed data; the valid height of the meaningful image.";
profiles[200]="RelatedSoundFile|-|40964|0xA004|audio|related sound file|related soundfile|related audio||Used to record the name of an audio file related to the image data.";
profiles[201]="FlashEnergy|-|41483|0xA20B|flash energy|flash||Indicates the strobe energy at the time the image is captured, as measured in Beam Candle Power Seconds";
profiles[202]="SpatialFrequencyResponse|-|41484|0xA20C|spatial frequency response|frequency response|spatial frequency|frequency|frequency response||Records the camera or input device spatial frequency table and SFR values in the direction of image width, image height, and diagonal direction, as specified in ISO 12233.";
profiles[203]="FocalPlaneXResolution|-|41486|0xA20E|focal plane x resolution|focal plane resolution||Indicates the number of pixels in the image width (X) direction per FocalPlaneResolutionUnit on the camera focal plane.";
profiles[204]="FocalPlaneYResolution|-|41487|0xA20F|focal plane y resolution|focal plane resolution||Indicates the number of pixels in the image height (Y) direction per FocalPlaneResolutionUnit on the camera focal plane.";
profiles[205]="FocalPlaneResolutionUnit|-|41488|0xA210|focal plane y resolution|focal plane resolution|focal plane resolution unit|resolution unit||Indicates the unit for measuring FocalPlaneXResolution and FocalPlaneYResolution.";
profiles[206]="SubjectLocation|-|41492|0xA214|subject location||Indicates the location of the main subject in the scene.";
profiles[207]="ExposureIndex|-|41493|0xA215|exposure index|exposure||Indicates the exposure index selected on the camera or input device at the time the image is captured.";
profiles[208]="SensingMethod|-|41495|0xA217|sensing method||Indicates the image sensor type on the camera or input device.";
profiles[209]="FileSource|-|41728|0xA300|file source|source||Indicates the image source.";
profiles[210]="SceneType|-|41729|0xA301|scene type|scene||Indicates the type of scene.";
profiles[211]="CFAPattern|-|41730|0xA302||Indicates the color filter array (CFA) geometric pattern of the image sensor when a one-chip color area sensor is used.";
profiles[212]="CustomRendered|-|41985|0xA401||Indicates the use of special processing on image data, such as rendering geared to output.";
profiles[213]="ExposureMode|-|41986|0xA402|exposure mode|exposure||Indicates the exposure mode set when the image was shot.";
profiles[214]="WhiteBalance|-|41987|0xA403|white balance||Indicates the white balance mode set when the image was shot.";
profiles[215]="DigitalZoomRatio|-|41988|0xA404|digital zoom ratio|digitalzoom|zoom ratio|zoomratio|zoom||Indicates the digital zoom ratio when the image was shot.";
profiles[216]="FocalLengthIn35mmFilm|-|41989|0xA405|focal length|focallength||Indicates the equivalent focal length assuming a 35mm film camera, in mm.";
profiles[217]="SceneCaptureType|-|41990|0xA406|scene capture type|capturetype|capture type|capture||Indicates the type of scene that was shot.";
profiles[218]="GainControl|-|41991|0xA407|gain control|gain||Indicates the degree of overall image gain adjustment.";
profiles[219]="Contrast|-|41992|0xA408||Indicates the direction of contrast processing applied by the camera when the image was shot.";
profiles[220]="Saturation|-|41993|0xA409||Indicates the direction of saturation processing applied by the camera when the image was shot.";
profiles[221]="Sharpness|-|41994|0xA40A||Indicates the direction of sharpness processing applied by the camera when the image was shot.";
profiles[222]="DeviceSettingDescription|-|41995|0xA40B||This tag indicates information on the picture-taking conditions of a particular camera model.";
profiles[223]="SubjectDistanceRange|-|41996|0xA40C|subject distance range|subject distance|subjectdistance|distance range|distancerange|distance||Indicates the distance to the subject.";
profiles[224]="ImageUniqueID|-|42016|0xA420|image unique id|uniqueid|unique id|imageid|image id|id||Indicates an identifier assigned uniquely to each image.";
profiles[225]="GPSVersionID|-|0|0x0000|gps version id|gpsversion|gps version|gps||Indicates the version of GPSInfoIFD.";
profiles[226]="GPSLatitudeRef|-|1|0x0001|gps latitude ref|latituderef|latitude ref|latitude||Indicates whether the latitude is north or south latitude.";
profiles[227]="GPSLatitude|-|2|0x0002|gps latitude|latitude||Indicates the latitude.";
profiles[228]="GPSLongitudeRef|-|3|0x0003|gps longitude ref|longituderef|longitude ref|longitude||Indicates whether the longitude is east or west longitude.";
profiles[229]="GPSLongitude|-|4|0x0004|gps longitude|longitude||Indicates the longitude.";
profiles[230]="GPSAltitudeRef|-|5|0x0005|gps altitude ref|altituderef|altitude ref|altitude||Indicates the altitude used as the reference altitude.";
profiles[231]="GPSAltitude|-|6|0x0006|gps altitude|altitude||Indicates the altitude based on the reference in GPSAltitudeRef.";
profiles[232]="GPSTimeStamp|-|7|0x0007|gps time stamp|timestamp|time stamp|time||Indicates the time as UTC (Coordinated Universal Time).";
profiles[233]="GPSSatellites|-|8|0x0008|gps satellites|satellites|satellite||Indicates the GPS satellites used for measurements.";
profiles[234]="GPSStatus|-|9|0x0009|gps status|status||Indicates the status of the GPS receiver when the image is recorded.";
profiles[235]="GPSMeasureMode|-|10|0x000A|gps measure mode|measuremode|measure mode||Indicates the GPS measurement mode.";
profiles[236]="GPSDOP|-|11|0x000B|gps dop|dop|hdop|pdop||Indicates the GPS DOP (data degree of precision).";
profiles[237]="GPSSpeedRef|-|12|0x000C|gps speed ref|speedref|speed ref|speed||Indicates the unit used to express the GPS receiver speed of movement.";
profiles[238]="GPSSpeed|-|13|0x000D|gps speed|speed||Indicates the speed of GPS receiver movement.";
profiles[239]="GPSTrackRef|-|14|0x000E|gps track ref|trackref|track ref|track||Indicates the reference for giving the direction of GPS receiver movement.";
profiles[240]="GPSTrack|-|15|0x000F|gps track|track||Indicates the direction of GPS receiver movement.";
profiles[241]="GPSImgDirectionRef|-|16|0x0010|gps img direction ref|imgdirectionref|img direction ref|directionref|direction ref|direction||Indicates the reference for giving the direction of the image when it is captured.";
profiles[242]="GPSImgDirection|-|17|0x0011|gps img direction|imgdirection|img direction|direction||Indicates the direction of the image when it was captured.";
profiles[243]="GPSMapDatum|-|18|0x0012|gps map datum|mapdatum|map datum|map||Indicates the geodetic survey data used by the GPS receiver.";
profiles[244]="GPSDestLatitudeRef|-|19|0x0013|gps dest latitude ref|destlatituderef|dest latitude ref|destlatitude|dest latitude|latituderef|latitude ref|latitude|dest||Indicates whether the latitude of the destination point is north or south latitude.";
profiles[245]="GPSDestLatitude|-|20|0x0014|gps dest latitude|destlatitude|dest latitude|latitude|dest||Indicates the latitude of the destination point.";
profiles[246]="GPSDestLongitudeRef|-|21|0x0015|gps dest longitude ref|destlongituderef|dest longitude ref|longituderef|longitude ref|destlongitude|dest longitude|longitude|dest||Indicates whether the longitude of the destination point is east or west longitude.";
profiles[247]="GPSDestLongitude|-|22|0x0016|gps dest longitude|destlongitude|dest longitude|longitude|dest||Indicates the longitude of the destination point.";
profiles[248]="GPSDestBearingRef|-|23|0x0017|gps dest bearing ref|destbearingref|dest bearing ref|bearingref|bearing ref|destbearing|dest bearing|dest|bearing||Indicates the reference used for giving the bearing to the destination point.";
profiles[249]="GPSDestBearing|-|24|0x0018|gps dest bearing|destbearing|dest bearing|dest|bearing||Indicates the bearing to the destination point.";
profiles[250]="GPSDestDistanceRef|-|25|0x0019|gps dest distance ref|destdistanceref|dest distance ref|destdistance|dest distance|distanceref|distance ref|dest|distance||Indicates the unit used to express the distance to the destination point.";
profiles[251]="GPSDestDistance|-|26|0x001A|gps dest distance|destdistance|dest distance|dest|distance||Indicates the distance to the destination point.";
profiles[252]="GPSProcessingMethod|-|27|0x001B|gps processing method|processingmethod|processing method|processing||A character string recording the name of the method used for location finding.";
profiles[253]="GPSAreaInformation|-|28|0x001C|gps area information|areainformation|area information||A character string recording the name of the GPS area.";
profiles[254]="GPSDateStamp|-|29|0x001D|gps date stamp|datestamp|date stamp|date||A character string recording date and time information relative to UTC (Coordinated Universal Time).";
profiles[255]="GPSDifferential|-|30|0x001E|gps differential|differential||Indicates whether differential correction is applied to the GPS receiver.";
//profiles[256]="InteroperabilityIndex|-|1|0x0001|interoperability||Indicates the identification of the Interoperability rule.";

ifdstart = new Array();
ifdname = new Array();
ifddir = new Array();
ifdstart[0]=0;
ifdname[0]="Image";
ifddir[0]="";

ifdstart[1]=169;
ifdname[1]="Exif";
ifddir[1]="privateifd/exif/";

ifdstart[2]=225;
ifdname[2]="GPS";
ifddir[2]="privateifd/gps/";

ifdstart[3]=256;
ifdname[3]="Interoperability";
ifddir[3]="privateifd/interoperability/";

ifdstart[4]=257;

// ExifVersion|-            |36864|0x9000|exif        |exif version|version||The version of the supported Exif standard.";
// Name        LibTiff name  Dec   Hex    ?    ?            ?      ? Desc
// Maker      |TIFFTAG_MAKE |271  |0x010F|manufacturer||The scanner manufacturer.";

// 4 först samma, sen ta sista för desc.

var Tags = {};

ifdIndex = 0;

profiles.forEach(function(p, i) {
  info = p.split('|');
  
  var name = info[0];
  var libtiffname = info[1];
  var dec = info[2];
  var hex = info[3];
  var desc = info[info.length - 1];

  var shortDesc = (libtiffname !== '-' && info[5] !== '') ? info[5] : info[4];
  
  if (i >= 169) ifdIndex = 1;
  if (i >= 225) ifdIndex = 2;
  if (i >= 256) ifdIndex = 3;
  if (i >= 257) ifdIndex = 4;

  var url = "http://www.awaresystems.be/imaging/tiff/tifftags/" + ifddir[ifdIndex] + name.toLowerCase().replace(/\s+/g, "") + ".html";

  Tags[dec] = {
    name: name,
    hex: hex,
    short_desc: shortDesc,
    desc: desc,
    url: url
  };
  // ifddir[s]+url+".html
  // console.log(hex + ": " + name + " - " + shortDesc + " - " + desc);
});

console.log(JSON.stringify(Tags, undefined, 2));
//console.log("nr of tags: " + Object.keys(Tags).length);
//console.log("nr of tags in array: " + profiles.length);

